require("dotenv").config({ path: require("path").resolve(__dirname, "../.env") });
const fs = require("fs");
const path = require("path");
const mongoose = require("mongoose");
const connectDB = require("../src/config/db");

async function generateManifest() {
  await connectDB();
  const db = mongoose.connection.db;

  const collections = await db.listCollections().toArray();
  const collectionNames = collections.map(c => c.name).sort();

  const manifest = {
    generatedAt: new Date().toISOString(),
    summary: {},
    proposedForDeletion: [],
    preservedRecords: [],
    manualReviewRecords: []
  };

  for (const collName of collectionNames) {
    if (collName.startsWith("system.")) continue;
    const docs = await db.collection(collName).find({}).toArray();

    manifest.summary[collName] = {
      total: docs.length,
      real: 0,
      test: 0,
      demo: 0,
      seed: 0,
      unknown: 0,
    };

    const coll = collName.toLowerCase();

    for (const doc of docs) {
      const id = doc._id.toString();
      let classification = "UNKNOWN";
      let reason = "";

      // Collection-specific classification rules:
      if (coll === "users") {
        if (doc.username === "admin") {
          classification = "REAL";
          reason = "Primary Administrative Account";
        } else if (
          doc.username?.startsWith("admin_wd_") ||
          doc.username?.startsWith("usthad_wd_") ||
          doc.username?.startsWith("inst_") ||
          doc.username?.includes("p2_215377") ||
          doc.email?.includes("215377@markaz.edu") ||
          doc.email?.startsWith("inst.1789") ||
          doc.email?.endsWith("@sanaviyya.test") ||
          doc.email === "test@misc.markaz.in" ||
          ["student001", "student0", "student_1788930050971", "student_1788930079158"].includes(doc.username) ||
          (!doc.username && !doc.email)
        ) {
          classification = "TEST";
          reason = (!doc.username && !doc.email)
            ? "Empty orphaned user record from early automated testing"
            : "Scripted test user created by automated E2E test scripts";
        } else if (
          doc.email?.endsWith("@gmail.com") ||
          doc.email?.endsWith("@yopmail.com") ||
          doc.email?.endsWith("@markaz.in")
        ) {
          classification = "REAL";
          reason = "Active business user (Faculty / Student / Parent / Institution)";
        } else {
          classification = "UNKNOWN";
          reason = "User account requiring manual review";
        }
      } else if (coll === "studentprofiles") {
        const studentName = (doc.nameEnglish || doc.fullName || doc.name || "").trim();
        const regNo = doc.registrationNumber || doc.admissionNo || "";
        if (
          studentName === "Offline User" ||
          studentName.startsWith("Socket User") ||
          studentName === "Fresh Student No Profile" ||
          studentName === "Student User" ||
          studentName.startsWith("Talib Outsider") ||
          studentName.includes("215377") ||
          regNo.startsWith("OUT_P3_") ||
          regNo.startsWith("REG_P2_") ||
          regNo.startsWith("TEST-")
        ) {
          classification = "TEST";
          reason = "Synthetic student profile generated by automated socket / phase tests";
        } else {
          classification = "REAL";
          reason = "Legitimate student profile linked to enrolled student";
        }
      } else if (coll === "parentprofiles") {
        classification = "REAL";
        reason = "Real parent profile linked to active student";
      } else if (coll === "facultyprofiles") {
        const facName = (doc.nameEnglish || doc.fullName || doc.name || "").trim();
        const fId = doc.facultyId || doc.employeeId || "";
        if (
          facName.startsWith("Usthad Outsider") ||
          facName.startsWith("Usthad Assigned") ||
          facName.startsWith("Usthad Unassigned") ||
          facName.startsWith("Usthad Authorized") ||
          facName.startsWith("Usthad Unauthorized") ||
          facName.startsWith("Usthad Peer") ||
          facName === "Usthad Ahmad Al-Kindi" ||
          facName.includes("215377") ||
          fId.startsWith("OUT_") ||
          fId.startsWith("FAC_P") ||
          fId.startsWith("UNAUTH_") ||
          fId.startsWith("PEER_") ||
          fId.startsWith("FAC-WD-")
        ) {
          classification = "TEST";
          reason = "Synthetic faculty profile created by testPhase2 / timetable test scripts";
        } else {
          classification = "REAL";
          reason = "Legitimate faculty profile (e.g. Usthad Ansar, Dr. Haseeb, Usthad Shihab)";
        }
      } else if (coll === "institutionprofiles") {
        const code = doc.institutionCode || doc.code || "";
        if (code === "MISC-TEST" || code === "INST-1856" || doc.type === "TEST" || doc.institutionName?.includes("Test")) {
          classification = "TEST";
          reason = "Synthetic test institution";
        } else {
          classification = "REAL";
          reason = "Legitimate institution campus";
        }
      } else if (coll === "academicyears") {
        if (["AY_215377", "AY8334"].includes(doc.yearCode) || doc.yearName?.includes("Test") || doc.yearName?.includes("AY-1791")) {
          classification = "TEST";
          reason = "Synthetic academic year generated during automated tests";
        } else {
          classification = "REAL";
          reason = "Official academic year (e.g. AY2026, AY26, AY-27)";
        }
      } else if (coll === "classes") {
        const clsName = doc.className || doc.name || "";
        const code = doc.code || doc.classCode || "";
        if (
          clsName.includes("215377") ||
          clsName.includes("Alpha (No Friday)") ||
          clsName.includes("Beta (Default Working Days)") ||
          clsName.includes("Gamma (No Wednesday)") ||
          code.includes("215377") ||
          code.includes("8334")
        ) {
          classification = "TEST";
          reason = "Synthetic class generated during automated timetable / working days testing";
        } else {
          classification = "REAL";
          reason = "Official standard / class curriculum (e.g. Standard 1, Standard 2, STD3, STD4)";
        }
      } else if (coll === "subjects") {
        const subCode = doc.subjectCode || doc.code || "";
        const subName = doc.subjectName || doc.name || "";
        if (subCode === "FQ_215377" || subCode === "FIQH-8334" || subName.includes("215377") || subCode.includes("8334")) {
          classification = "TEST";
          reason = "Synthetic subject created during automated tests";
        } else {
          classification = "REAL";
          reason = "Official syllabus subject (e.g. ARB 101, ENG 1)";
        }
      } else if (coll === "facultyassignments") {
        // Test assignment linked to S1_215377
        if (id === "6ac076c85a7919b3e80a2572") {
          classification = "TEST";
          reason = "Synthetic faculty assignment created during Phase 2 test suite";
        } else {
          classification = "REAL";
          reason = "Official faculty class assignment";
        }
      } else if (coll === "timetables") {
        if (
          id === "6ac076c85a7919b3e80a2577" || // assigned to S1_215377
          id === "6ac5bb424a9d02a685807abf"   // test Friday entry
        ) {
          classification = "TEST";
          reason = "Synthetic timetable schedule created during automated test execution";
        } else {
          classification = "REAL";
          reason = "Official class timetable schedule";
        }
      } else if (coll === "notifications") {
        // 4 real notifications: fasi leave submitted, fasi leave approved, babu leave approved, haseeb timetable assigned
        const realNotifIds = [
          "6ac4d9c4745e892deed11bed",
          "6ac5c16a4a9d02a685807bcc",
          "6ac5c16a4a9d02a685807bd1",
          "6ac5bb424a9d02a685807ac9"
        ];
        if (realNotifIds.includes(id)) {
          classification = "REAL";
          reason = "Legitimate operational notification";
        } else {
          classification = "TEST";
          reason = "Automated test notification artifact";
        }
      } else if (coll === "emailevents") {
        const realEmailIds = [
          "6ac5bb464a9d02a685807ad3",
          "6ac5c16f4a9d02a685807bd8"
        ];
        if (realEmailIds.includes(id)) {
          classification = "REAL";
          reason = "Legitimate business email event";
        } else {
          classification = "TEST";
          reason = "Automated test email event dispatch";
        }
      } else if (coll === "exams") {
        classification = "REAL";
        reason = "Official Sanaviyya Board Examination (EXAM-26)";
      } else if (coll === "examschedules" || coll === "examregistrations") {
        // Check if examRegistration 6abcab8fd7f043e3387561d8 is test
        if (id === "6abcab8fd7f043e3387561d8") {
          classification = "TEST";
          reason = "Exam registration generated by Phase 4 test script";
        } else {
          classification = "REAL";
          reason = "Official student examination registrations / schedule";
        }
      } else if (coll === "leaves") {
        classification = "REAL";
        reason = "Official student leave application";
      } else if (coll === "attendancerecords") {
        classification = "REAL";
        reason = "Official student attendance log";
      } else if (coll === "payments") {
        classification = "REAL";
        reason = "Official student payment / fee transaction";
      } else if (coll === "syllabuses") {
        classification = "REAL";
        reason = "Official academic syllabus";
      } else if (
        [
          "campuses",
          "institutesettings",
          "studentdevelopmentscores",
          "markcorrectionrequests",
          "accountsetuptokens",
          "enquiries"
        ].includes(coll)
      ) {
        classification = "REAL";
        reason = "Legitimate institutional data";
      }

      // Update counters
      const lowerClass = classification.toLowerCase();
      if (manifest.summary[collName][lowerClass] !== undefined) {
        manifest.summary[collName][lowerClass]++;
      } else {
        manifest.summary[collName].unknown++;
      }

      const recordItem = {
        collection: collName,
        id,
        classification,
        reason,
        identifier: doc.name || doc.fullName || doc.username || doc.email || doc.title || doc.code || doc.yearCode || id,
        createdAt: doc.createdAt || null
      };

      if (classification === "TEST" || classification === "DEMO" || classification === "DEV") {
        manifest.proposedForDeletion.push(recordItem);
      } else if (classification === "REAL") {
        manifest.preservedRecords.push(recordItem);
      } else {
        manifest.manualReviewRecords.push(recordItem);
      }
    }
  }

  const manifestPath = path.resolve(__dirname, "cleanup_manifest.json");
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), "utf8");

  console.log("=== CLEANUP MANIFEST GENERATED ===");
  console.log(`Saved to: ${manifestPath}`);
  console.log(`Total proposed for deletion: ${manifest.proposedForDeletion.length}`);
  console.log(`Total preserved (REAL): ${manifest.preservedRecords.length}`);
  console.log(`Total for manual review (UNKNOWN): ${manifest.manualReviewRecords.length}`);
  console.log("\nSummary by Collection:");
  console.table(manifest.summary);

  await mongoose.disconnect();
}

generateManifest().catch(err => {
  console.error("Error generating manifest:", err);
  process.exit(1);
});
