const USER_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  PENDING_SETUP: "PENDING_SETUP",
  BLOCKED: "BLOCKED",
});

const OTP_PURPOSE = Object.freeze({
  LOGIN_2FA: "LOGIN_2FA",
  EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
  MOBILE_VERIFICATION: "MOBILE_VERIFICATION",
  PASSWORD_RESET: "PASSWORD_RESET",
  ACCOUNT_SETUP: "ACCOUNT_SETUP",
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
});

module.exports = {
  USER_STATUS,
  OTP_PURPOSE,
  PAYMENT_STATUS,
};
